
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
bird_typ = input("Enter a type of bird: ")
room = input("Enter a room in the house: ")
verb_past_tense = input("Enter a verb in past tense: ")
verb = input("Enter a verb: ")
relative_name = input("Enter a relative's name: ")
noun1 = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
verb_ing1 = input("Enter a verb ending in -ing: ")
body_part = input("Enter a plural part of the body: ")
noun_plu = input("Enter a plural noun: ")
verb_ing2 = input("Enter another verb ending in -ing: ")
noun2 = input("Enter another noun: ")

print("It was a "+adjective1+", cold November day. I woke to the "+adjective2+" smell of "+bird_typ+" roasting in "+room+" downstairs.")
print("I "+verb_past_tense+" down the stairs to see if I could help "+verb+" the dinner.")
print("My mom said, \"See if "+relative_name+" needs a fresh "+noun1+".\"")
print("So I carried a tray of glasses full of "+liquid+" into the "+verb_ing1+" room.")
print("When I got there, I couldn't believe my "+body_part+"!")
print("There were "+noun_plu+" "+verb_ing2+" on the "+noun2+"!")
